exclude: |
  (?x)
  .html$|.csv$|.svg$|.md$|.txt$|.json$|.xml$|.pickle$|^.github/|
  (LICENSE.*|README.*)
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        entry: nbstripout
        language: python
        types: [jupyter]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        files: ^featuretools/
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma
        name: Add trailing comma
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.3'
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args:
          - --fix
          - --config=./pyproject.toml
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
        args:
          - --config=./pyproject.toml
