# .pre-commit-config.yaml
exclude: ^LICENSES/|\.(html|csv|svg|md|)$
default_stages: [commit]
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--target-version=py310]
