name: Auto Approve Dependency PRs
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Find dependency PRs
      id: find_prs
      run: |
        gh pr list --author "machineFL" --base main --state open --search "status:success review:required" --limit 1 --json url > dep_PRs_waiting_approval.json
        DEP_PULL_REQUEST_URL=$(cat dep_PRs_waiting_approval.json | grep -Eo "(https)://[a-zA-Z0-9./?=_%:-]*")
        if [[ "${DEP_PULL_REQUEST_URL}" -gt 8 ]]; then
          echo "::set-output name=DEP_PULL_REQUEST_URL::$(DEP_PULL_REQUEST_URL)"
        else 
          echo "No matching PR found"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
    - name: Approve dependency PRs and enable auto-merge 
      if: steps.find_prs.outputs.DEP_PULL_REQUEST_URL && steps.find_prs.outputs.DEP_PULL_REQUEST_URL != null
      run: |
        gh pr review ${{ steps.find_prs.outputs.DEP_PULL_REQUEST_URL }} --approve --comment --body "auto approve"
        gh pr merge ${{ steps.find_prs.outputs.DEP_PULL_REQUEST_URL }} --auto --squash
        rm dep_PRs_waiting_approval.json
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
