on:
  workflow_dispatch:
    inputs:
      pypi_version:
        description: 'released PyPI version to use (include v, example v1.11.1)'
        required: true

name: Create Feedstock PR
jobs:
  create_feedstock_pr:
    name: Create Feedstock PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout inputted version
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.inputs.pypi_version }}
          path: "./featuretools"
      - name: Pull latest from upstream for user forked feedstock
        run: |
          gh auth status
          gh repo fork conda-forge/featuretools-feedstock --clone
          gh repo sync machineAYX/featuretools-feedstock --branch main --source conda-forge/featuretools-feedstock --force
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: machineAYX/featuretools-feedstock
          ref: main
          path: "./featuretools-feedstock"
          fetch-depth: '0'
      - name: Run Create Feedstock meta YAML
        id: create-feedstock-meta
        uses: alteryx/create-feedstock-meta-yaml@v3
        with:
          project: "featuretools"
          pypi_version: ${{ github.event.inputs.pypi_version }}
          setup_cfg_filepath: "featuretools/setup.cfg"
          meta_yaml_filepath: "featuretools-feedstock/recipe/meta.yaml"
          add_to_test_requirements: "graphviz !=2.47.2"
      - name: View updated meta yaml
        run: cat featuretools-feedstock/recipe/meta.yaml
      - name: Push updated yaml
        run: |
          cd featuretools-feedstock
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.email "machineOSS@alteryx.com"
          git config --global user.name "machineAYX Bot"
          git remote set-url origin https://${{ secrets.AUTO_APPROVE_TOKEN }}@github.com/machineAYX/featuretools-feedstock
          git checkout -b conda-autocreate-${{ github.event.inputs.pypi_version }}
          git add recipe/meta.yaml
          git commit -m "auto commit"
          git push origin conda-autocreate-${{ github.event.inputs.pypi_version }}
      - name: Adding URL to job output
        run: |
          echo "Conda Feedstock Pull Request: https://github.com/machineAYX/featuretools-feedstock/pull/new/conda-autocreate-${{ github.event.inputs.pypi_version }}" >> $GITHUB_STEP_SUMMARY
