on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      pypi_version:
        description: 'released PyPI version to use'
        required: true
        
name: Create Feedstock PR
jobs:
  create_feedstock_pr:
    name: Create Feedstock PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout published version
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: "v1.12.0"
      - if: ${{ github.event.inputs.pypi_version }}
        name: Checkout inputted version
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.inputs.pypi_version }}
      - name: Pull latest from upstream for user forked feedstock
        run: |
          gh auth status
          gh repo fork conda-forge/featuretools-feedstock --clone
          gh repo sync machineAYX/featuretools-feedstock --branch main --source conda-forge/featuretools-feedstock --branch main --force
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: machineAYX/featuretools-feedstock
          ref: main
      - name: Run Create Feedstock meta YAML
        id: create-feedstock-meta
        uses: alteryx/create-feedstock-meta-yaml@v2
        with:
          project: "featuretools"
          pypi_version: "v1.12.0"
          setup_cfg_filepath: "setup.cfg"
          meta_yaml_filepath: "featuretools-feedstock/recipe/meta.yaml"
          add_to_test_requirements: "python-graphviz >=0.8.4"
