on:
  pull_request:
    types: [opened, synchronize]

name: Create Feedstock PR
jobs:
  pull_latest_main:
    name: Pull latest in forked feestock
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.8"
      - uses: actions/checkout@v3
        with:
          repository: 'alteryx/featuretools'
          ref: "${{ github.event.release.tag_name }}"
      - uses: actions/checkout@v3
        with:
          repository: 'alteryx/featuretools-feedstock'
          ref: 'master'          
      - name: Pull latest from upstream for alteryx forked feestock
        run: |
          gh auth status
          gh repo clone conda-forge/featuretools-feedstock --depth 1
          gh repo sync machineAYX/featuretools-feedstock --branch main --source conda-forge/featuretools-feedstock --branch main
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
      - name: Install conda_forge_tick
        run: |
          git clone --depth 1 https://github.com/regro/cf-scripts.git
          cd cf-scripts
          conda install -c conda-forge --file requirements/run
      - name: Create branch
        run: |
          gh pr create --repo alteryx/featuretools-feedstock
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
