on:
  pull_request:
    types: [opened, synchronize]

name: Create Feedstock PR
jobs:
  create_feedstock_pr:
    name: Pull latest in forked feestock, and create feedstock PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "${{ github.action_repository  }}"
          ref: "${{ github.event.release.tag_name }}"
      - name: Pull latest from upstream for user forked feedstock
        run: |
          gh auth status
          rm -rf featuretools-feedstock
          gh repo fork conda-forge/featuretools-feedstock --clone
          gh repo sync machineAYX/featuretools-feedstock --branch main --source conda-forge/featuretools-feedstock --branch main --force
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
