on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Install Test
jobs:
  install_ft_complete:
    name: ${{ matrix.python_version }} install featuretools complete
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build featuretools package
        run: make package_featuretools
      - name: Install complete version of featuretools
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install -e unpacked_sdist/[complete]
      - name: Test by importing packages
        run: |
          python -c "import featuretools_tsfresh_primitives"
          python -c "import alteryx_open_src_update_checker"
          python -c "import categorical_encoding"
          python -c "import nlp_primitives"
          python -c "import autonormalize"
          python -c "import featuretools_sklearn_transformer"
        env:
          ALTERYX_OPEN_SRC_UPDATE_CHECKER: False
