on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Unit Tests - Latest Dependencies
jobs:
  lint_test:
    name: ${{ matrix.python_version }} lint test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build featuretools package
        run: make package_featuretools
      - name: Install featuretools with optional, dev, and test requirements
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install -e unpacked_sdist/[koalas]
          python -m pip install -r unpacked_sdist/dev-requirements.txt
          python -m pip install -r unpacked_sdist/test-requirements.txt
      - name: Run lint test
        run: make lint

  unit_tests:
    name: ${{ matrix.python_version }} unit tests ${{ matrix.libraries }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8"]
        libraries: ["core", "dask", "koalas"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build featuretools package
        run: make package_featuretools
      - name: Set up pip and graphviz
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          sudo apt update && sudo apt install -y graphviz
      - name: Install featuretools - requirements
        run: |
          python -m pip install -e unpacked_sdist/
      - name: Install featuretools - tests requirements
        run: |
          python -m pip install -r unpacked_sdist/test-requirements.txt
      - if: ${{ matrix.libraries == 'koalas' }}
        name: Install featuretools - koalas requirements
        run: |
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          python -m pip install -e unpacked_sdist/[koalas]
      - if: ${{ matrix.libraries == 'dask' }}
        name: Install featuretools - dask requirements
        run: |
          python -m pip install -e unpacked_sdist/[dask]
      - if: ${{ matrix.python_version != 3.7 }}
        name: Run unit tests (no code coverage)
        run: |
          cd unpacked_sdist
          pytest woodwork/ -n 2
      - if: ${{ matrix.python_version == 3.7 }}
        name: Run unit tests with code coverage
        run: |
          python -m pip install "$(cat dev-requirements.txt | grep codecov)"
          coverage erase
          cd unpacked_sdist/
          coverage erase
          pytest woodwork/ -n 2 --cov=woodwork --cov-config=../.coveragerc
      - if: ${{ matrix.python_version == 3.7 }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  win_unit_tests:
    name: ${{ matrix.python_version }} windows unit tests
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8"]
    steps:
      - name: Download miniconda
        shell: pwsh
        run: |
          $File = "Miniconda3-4.7.12.1-Windows-x86_64.exe"
          $Uri = "https://repo.anaconda.com/miniconda/$File"
          $ProgressPreference = "silentlyContinue"
          Invoke-WebRequest -Uri $Uri -Outfile "$env:USERPROFILE/$File"
          $hashFromFile = Get-FileHash "$env:USERPROFILE/$File" -Algorithm SHA256
          $hashFromUrl = "f18060cc0bb50ae75e4d602b7ce35197c8e31e81288d069b758594f1bb46ab45"
          if ($hashFromFile.Hash -ne "$hashFromUrl") {
            Throw "File hashes did not match!"
          }
      - name: Install miniconda
        shell: cmd
        run: start /wait "" %UserProfile%\Miniconda3-4.7.12.1-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3
      - name: Create python ${{ matrix.python_version }} environment
        shell: pwsh
        run: |
          . $env:USERPROFILE\Miniconda3\shell\condabin\conda-hook.ps1
          conda create -n featuretools python=${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install featuretools with test requirements
        shell: pwsh
        run: |
          . $env:USERPROFILE\Miniconda3\shell\condabin\conda-hook.ps1
          conda activate featuretools
          conda config --add channels conda-forge
          conda install python-graphviz -q -y
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install -r test-requirements.txt
      - name: Run unit tests
        run: |
          . $env:USERPROFILE\Miniconda3\shell\condabin\conda-hook.ps1
          conda activate featuretools
          pytest featuretools\ -n 2
