on:
  release:
    types: [published]

name: Release
jobs:
  pypi:
    name: PyPI Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyPI Upload
      uses: FeatureLabs/gh-action-pypi-upload@v1
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        TEST_PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
