name: Release Notes Updated
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  release_notes_updated:
    name: release notes updated
    runs-on: ubuntu-latest
    steps:
      - name: Check for development branch
        id: branch
        shell: python
        run: |
          from re import compile
          main = '^main$'
          release = '^release_v\d+\.\d+\.\d+$'
          backport = '^backport_v\d+\.\d+\.\d+$'
          dep_update = '^latest-dep-update-[a-f0-9]{7}$'
          min_dep_update = '^min-dep-update-[a-f0-9]{7}$'
          regex = main, release, backport, dep_update, min_dep_update
          patterns = list(map(compile, regex))
          ref = "${{ github.event.pull_request.head.ref }}"
          is_dev = not any(pattern.match(ref) for pattern in patterns)
          print('::set-output name=is_dev::' + str(is_dev))
      - if: ${{ steps.branch.outputs.is_dev == 'true' }}
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - if: ${{ steps.branch.outputs.is_dev == 'true' }}
        name: Check if release notes were updated
        run: cat docs/source/release_notes.rst | grep ":pr:\`${{ github.event.number }}\`"
        
