name: Tests - Featuretools with Woodwork main branch
on:
  workflow_dispatch:
jobs:
  tests_woodwork_main:
    if: ${{ github.repository_owner == 'alteryx' }}
    name: ${{ matrix.python_version }} tests ${{ matrix.libraries }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build featuretools package
        run: make package
      - name: Set up pip and graphviz
        run: |
          pip config --site set global.progress_bar off
          python -m pip install -U pip
          sudo apt update && sudo apt install -y graphviz
      - name: Install Woodwork & Featuretools - test requirements
        run: |
          python -m pip install -e unpacked_sdist/[test,dask]
          python -m pip uninstall -y woodwork
          python -m pip install https://github.com/alteryx/woodwork/archive/main.zip
      - name: Log test run info
        run: |
          echo "Run unit tests without code coverage for ${{ matrix.python_version }}"
          echo "Testing with woodwork version:" `python -c "import woodwork; print(woodwork.__version__)"`
      - name: Run unit tests without code coverage
        run: pytest featuretools/ -n auto

  slack_alert_failure:
    name: Send Slack alert if failure
    needs: tests_woodwork_main
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Send Slack alert if failure
        if: ${{ needs.tests_woodwork_main.result != 'success' }}
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
