name: Tests - Minimum Dependencies
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  py39_tests_minimum_dependencies:
    name: Tests - 3.9 Minimum Dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Config pip, upgrade pip, and install graphviz
        run: |
          sudo apt update
          sudo apt install -y graphviz
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install wheel
      - name: Install featuretools with no dependencies
        run: |
          python -m pip install -e . --no-dependencies
      - name: Install featuretools - minimum tests dependencies
        run: |
          python -m pip install -r featuretools/tests/requirement_files/minimum_test_requirements.txt
      - name: Install featuretools - minimum core dependencies
        run: |
          python -m pip install -r featuretools/tests/requirement_files/minimum_core_requirements.txt
      - name: Run unit tests without code coverage
        run: python -m pytest -x -n auto featuretools/tests/