name: Test Featuretools with Woodwork main Branch
on:
  schedule:
    - cron: "0 * * * *"
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  scheduled_unit_latest_tests:
    name: ${{ matrix.python_version }} unit tests ${{ matrix.libraries }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.7", "3.8", "3.9",]
        libraries: ["core", "dask", ]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build featuretools package
        run: make package_featuretools
      - name: Set up pip and graphviz
        run: |
          pip config --site set global.progress_bar off
          python -m pip install -U pip
          sudo apt update && sudo apt install -y graphviz

      - if: ${{ matrix.libraries == 'core' }}
        name: Install Woodwork & Featuretools - test requirements
        run: |
          python -m pip install -e unpacked_sdist/
          python -m pip install -r unpacked_sdist/test-requirements.txt
          python -m pip install -U git+https://github.com/alteryx/woodwork
      - if: ${{ matrix.libraries == 'dask' }}
        name: Install Woodwork & Featuretools - dask requirements
        run: |
          python -m pip install -e unpacked_sdist/
          python -m pip install -r unpacked_sdist/test-requirements.txt
          python -m pip install -U git+https://github.com/alteryx/woodwork dask[dataframe]>=2021.10.0
      - if: ${{ matrix.libraries == 'koalas' && matrix.python_version != '3.10' }}
        name: Install Woodwork & Featuretools with koalas pkg - koalas requirements
        run: |
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          PYSPARK_SUBMIT_ARGS="--master local[2] pyspark-shell"
          python -m pip install -e unpacked_sdist/[koalas]
          python -m pip install -r unpacked_sdist/test-requirements.txt -r unpacked_sdist/koalas-requirements.txt
          python -m pip install -U git+https://github.com/alteryx/woodwork
      - if: ${{ !( matrix.libraries == 'koalas' && matrix.python_version == '3.10') }}
        name: Run unit tests without code coverage
        run: |
          echo "Run unit tests without code coverage for ${{ matrix.python_version }} and ${{ matrix.libraries }}"
          echo "Testing with woodwork version:" `python -c "import woodwork; print(woodwork.__version__)"`
          pytest featuretools/ -n 2
