name: Unit Tests - Minimum Dependencies
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  py37_unit_tests_minimum_dependencies:
    name: 3.7 unit tests minimum dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libraries: ["core", "koalas"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Config pip, upgrade pip, and install graphviz
        run: |
          sudo apt update
          sudo apt install -y graphviz
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install "$(cat featuretools/tests/requirement_files/minimum_test_requirements.txt | grep wheel)"
      - name: Install featuretools with no dependencies
        run: |
          python -m pip install -e . --no-dependencies
      - if: ${{ matrix.libraries == 'koalas' }}
        name: Install numpy for koalas
        run: |
          NUMPY_VERSION=$(cat featuretools/tests/requirement_files/minimum_koalas_requirements.txt | grep numpy)
          python -m pip uninstall numpy -y
          python -m pip install $NUMPY_VERSION --no-build-isolation
      - if: ${{ matrix.libraries == 'core' }}
        name: Install numpy for core
        run: |
          NUMPY_VERSION=$(cat featuretools/tests/requirement_files/minimum_core_requirements.txt | grep numpy)
          python -m pip uninstall numpy -y
          python -m pip install $NUMPY_VERSION --no-build-isolation
      - name: Install featuretools - minimum tests dependencies
        run: |
          python -m pip install -r featuretools/tests/requirement_files/minimum_test_requirements.txt
      - if: ${{ matrix.libraries == 'koalas' }}
        name: Install featuretools - minimum koalas, core dependencies
        run: |
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          python -m pip install -r featuretools/tests/requirement_files/minimum_koalas_requirements.txt
      - if: ${{ matrix.libraries == 'core' }}
        name: Install featuretools - minimum core dependencies
        run: |
          python -m pip install -r featuretools/tests/requirement_files/minimum_core_requirements.txt
      - name: Run unit tests without code coverage
        run: |
          python -m pytest -x -n 2 featuretools/tests/
