name: Unit Tests - Featuretools with Woodwork main branch
on:
  workflow_dispatch:
jobs:
  unit_tests_woodwork_main:
    if: ${{ github.repository_owner == 'alteryx' }}
    name: ${{ matrix.python_version }} unit tests ${{ matrix.libraries }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.8", "3.9", "3.10"]
        libraries: ["core", "spark - misc", "spark - computational", "spark - entityset_1", "spark - entityset_2", "spark - primitives"]

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build featuretools package
        run: make package
      - name: Set up pip and graphviz
        run: |
          pip config --site set global.progress_bar off
          python -m pip install -U pip
          sudo apt update && sudo apt install -y graphviz
      - if: ${{ startsWith(matrix.libraries, 'spark')}}
        name: Install Woodwork & Featuretools with spark pkg - spark requirements
        run: |
          sudo apt install -y openjdk-11-jre-headless
          JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          PYSPARK_SUBMIT_ARGS="--master local[2] pyspark-shell"
          python -m pip install -e unpacked_sdist/[spark]
      - name: Install Woodwork & Featuretools - test requirements
        run: |
          python -m pip install -e unpacked_sdist/[test]
          python -m pip uninstall -y woodwork
          python -m pip install https://github.com/alteryx/woodwork/archive/main.zip
      - name: Log test run info
        run: |
          echo "Run unit tests without code coverage for ${{ matrix.python_version }} and ${{ matrix.libraries }}"
          echo "Testing with woodwork version:" `python -c "import woodwork; print(woodwork.__version__)"`
      - if: ${{ matrix.libraries == 'core' }}
        name: Run unit tests without code coverage
        run: pytest featuretools/ -n auto
      - if: ${{ matrix.libraries == 'spark - misc' }}
        name: Run unit tests (misc)
        run: pytest featuretools/ -n auto --ignore=featuretools/tests/computational_backend --ignore=featuretools/tests/entityset_tests --ignore=featuretools/tests/primitive_tests
      - if: ${{ matrix.libraries == 'spark - computational' }}
        name: Run unit tests (computational backend)
        run: pytest featuretools/tests/computational_backend/ -n auto
      - if: ${{ matrix.libraries == 'spark - entityset_1' }}
        name: Run unit tests (entityset batch 1)
        run: pytest featuretools/tests/entityset_tests -n auto --ignore=featuretools/tests/entityset_tests/test_es.py --ignore=featuretools/tests/entityset_tests/test_ww_es.py
      - if: ${{ matrix.libraries == 'spark - entityset_2' }}
        name: Run unit tests (entityset batch 2)
        run: pytest featuretools/tests/entityset_tests/test_es.py featuretools/tests/entityset_tests/test_ww_es.py
      - if: ${{ matrix.libraries == 'spark - primitives' }}
        name: Run unit tests (primitives)
        run: pytest featuretools/tests/primitive_tests -n auto

  slack_alert_failure:
    name: Send Slack alert if failure
    needs: unit_tests_woodwork_main
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Send Slack alert if failure
        if: ${{ needs.unit_tests_woodwork_main.result != 'success' }}
        id: slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
